/*!
 * \file BatCommands.cpp
 * \brief Implementation of BatCommands.h: the table of batch commands.
 *
 * Application by Coga Fation (developed with the help of ChatGPT and Claude).
 */

#include "BatCommands.h"

#include <algorithm>
#include <set>
#include <string>

namespace {

/*! \brief The reference, grouped by category (order = order in the pane). */
const std::vector<BatCommand> kCommands = {
    { "Flow", "if", "if  (\n    \n) else (\n    \n)",
      "Runs commands only when a condition is true.",
      "Syntax:\n  if [not] errorlevel N command\n  if [not] \"a\"==\"b\" command\n  if [not] exist file command\n  if [not] defined VAR command\n  if a EQU|NEQ|LSS|LEQ|GTR|GEQ b command (numeric compare)\n  if /i ... ignores case\nThe opening parenthesis of a block must be on the same line as if / else, and \"else\" on the line of the closing parenthesis.",
      "if exist \"C:\\temp\\a.txt\" (\n    echo found\n) else (\n    echo missing\n)" },
    { "Flow", "else", "else (\n    \n)",
      "Commands to run when the preceding if is false.",
      "Must be written as \") else (\" on the same line as the closing parenthesis of the if block.",
      "if errorlevel 1 (\n    echo FAIL\n) else (\n    echo PASS\n)" },
    { "Flow", "for", "for %%f in (*.txt) do echo %%f",
      "Repeats a command for every item of a set.",
      "Forms:\n  for %%v in (set) do cmd        items / wildcards\n  for /d %%v in (set) do cmd     folders\n  for /r [dir] %%v in (set) do   recursive\n  for /l %%v in (start,step,end) do   counter\n  for /f \"options\" %%v in (file|\"string\"|'command') do   lines of a file or of a command's output\nIn a batch file the variable needs two percent signs (%%f), on the command line one.",
      "for /l %%i in (1,1,5) do echo try %%i\nfor /f \"tokens=*\" %%a in ('hostname') do set \"HOST=%%a\"" },
    { "Flow", "goto", "goto :end",
      "Jumps to a label (a line starting with a colon).",
      "goto :eof ends the batch file (or the called subroutine) without defining the label. Labels are not case sensitive.",
      "if errorlevel 1 goto :fail\necho PASS\ngoto :eof\n:fail\necho FAIL" },
    { "Flow", "call", "call :subroutine arg1 arg2",
      "Runs another batch file or a labelled subroutine, then comes back.",
      "call file.bat args   runs another batch file and returns.\ncall :label args       runs the lines from the label up to goto :eof / exit /b; the arguments are %1, %2 ... inside.\nWithout call, running another .bat ends the current one.",
      "call :log PASS the test passed\ngoto :eof\n:log\necho %date% %time% %*>>\"%RESULT_FILE%\"\ngoto :eof" },
    { "Flow", "exit", "exit /b 0",
      "Ends the batch file (/b) or the whole cmd.exe and sets the exit code.",
      "exit /b N  ends only the batch file with exit code N (what a caller sees in %errorlevel%).\nexit N      closes the cmd.exe window too.\nBy convention 0 = success, anything else = failure.",
      "if not exist \"%FILE%\" exit /b 1\nexit /b 0" },
    { "Flow", "not", "not",
      "Negates the condition of an if.",
      "Only valid right after \"if\": if not exist file ...",
      "if not exist \"data.csv\" echo missing" },
    { "Flow", "exist", "exist \"file\"",
      "Condition of if: true if the file or folder exists.",
      "Use a trailing backslash to test for a folder: if exist \"C:\\temp\\\" ...",
      "if exist \"%~dp0result.txt\" echo there" },
    { "Flow", "defined", "defined VAR",
      "Condition of if: true if the environment variable is set.",
      "Write the name without percent signs.",
      "if not defined RESULT_FILE set \"RESULT_FILE=%~dp0result.txt\"" },
    { "Flow", "errorlevel", "if errorlevel 1",
      "Exit code of the last command.",
      "\"if errorlevel 1\" is true when the code is 1 OR MORE. The variable %errorlevel% holds the number and can be compared with EQU / NEQ.",
      "ping -n 1 host >nul\nif errorlevel 1 (echo FAIL) else (echo PASS)" },
    { "Flow", "shift", "shift",
      "Moves the batch arguments one position: %2 becomes %1.",
      "Used to loop over an unknown number of arguments.",
      ":next\nif \"%~1\"==\"\" goto :eof\necho %~1\nshift\ngoto :next" },
    { "Flow", "setlocal", "setlocal EnableDelayedExpansion",
      "Starts a local environment: variables set afterwards are discarded by endlocal.",
      "EnableDelayedExpansion lets you read a variable changed inside a block or loop with !VAR! instead of %VAR%.",
      "setlocal EnableDelayedExpansion\nset /a n=0\nfor %%f in (*.txt) do set /a n+=1\necho !n! files" },
    { "Flow", "endlocal", "endlocal",
      "Ends the environment started by setlocal and restores the variables.",
      "It is done automatically at the end of the batch file.",
      "endlocal" },
    { "Flow", "pushd", "pushd \"C:\\temp\"",
      "Changes folder and remembers the previous one (also for network paths).",
      "popd comes back.",
      "pushd \"%~dp0\"\ndir\npopd" },
    { "Flow", "popd", "popd",
      "Returns to the folder saved by the last pushd.",
      "",
      "popd" },
    { "Flow", "choice", "choice /c YN /m \"Continue\"",
      "Asks for a key and sets the errorlevel.",
      "/c keys  the valid keys; errorlevel = position of the key pressed (1 for the first).\n/t seconds /d key   answer by itself after a timeout.\n/n hide the list of keys.\nNot usable in Process Launcher (the command gets no keyboard).",
      "choice /c YN /t 10 /d N /m \"Continue\"\nif errorlevel 2 exit /b 1" },
    { "Flow", "pause", "pause",
      "Waits for a key. Do NOT use it in a batch file run by Process Launcher.",
      "Process Launcher gives the command no keyboard input: the command would end at once. Use timeout /t N instead when a wait is needed.",
      "timeout /t 5 /nobreak >nul" },
    { "Output", "echo", "echo ",
      "Prints text, or switches the display of commands on / off.",
      "echo text      prints text (an empty line: echo.)\necho off        stops showing the commands (put @ before it to hide even this line)\nTo print < > | & ^ put ^ before them. The exact text printed is what Process Launcher searches.",
      "@echo off\necho PASS" },
    { "Output", "@echo off", "@echo off",
      "First line of almost every batch file: stops showing the commands.",
      "Without it every command is printed before it runs, and Process Launcher would find your expected text inside the echoed command, giving a false PASS.",
      "@echo off" },
    { "Output", "rem", "rem ",
      "Comment line (also ::).",
      "Nothing after rem is run. \"::\" is a faster comment but must not be used inside a ( ) block.",
      "rem this file checks the disk space" },
    { "Output", "type", "type \"file.txt\"",
      "Prints the content of a text file.",
      "",
      "type \"%~dp0result.txt\"" },
    { "Output", "more", "more",
      "Shows the output one page at a time. Not useful in Process Launcher.",
      "Prefer type, or find /c to count lines.",
      "type big.txt | more" },
    { "Output", "cls", "cls",
      "Clears the screen.",
      "",
      "cls" },
    { "Output", "title", "title Test 1",
      "Sets the title of the console window.",
      "",
      "title Checking the network" },
    { "Output", "color", "color 0A",
      "Sets the console colours (background digit, text digit).",
      "0 black, 1 blue, 2 green, 3 aqua, 4 red, 5 purple, 6 yellow, 7 white, 8 gray, A-F light versions.",
      "color 0A" },
    { "Variables", "set", "set \"NAME=value\"",
      "Defines, shows or computes a variable.",
      "set \"A=text\"     define (the quotes keep trailing spaces out)\nset A           show variables that start with A\nset /a X=1+2     arithmetic ( + - * / %% )\nset /p V=Prompt  reads a line from the keyboard (not usable in Process Launcher)\nset \"A=\"        deletes A\nRead a variable with %A%; substring %A:~2,3%; replace %A:old=new%.",
      "set \"FILE=%~dp0result.txt\"\nset /a TOTAL=%OK%+%BAD%" },
    { "Variables", "%~dp0", "%~dp0",
      "The folder of the running batch file, with a trailing backslash.",
      "Modifiers of %0 / %1: %~f full path, %~d drive, %~p path, %~n name, %~x extension, %~nx name.extension, %~dp folder, %~z size, %~t date.",
      "cd /d \"%~dp0\"" },
    { "Variables", "%1", "%1",
      "The first argument passed to the batch file (%2, %3 ... up to %9).",
      "%* is all the arguments; %~1 removes the quotes; %0 is the batch file itself. An argument that is missing is empty.",
      "if \"%~1\"==\"\" (echo usage: %~nx0 host & exit /b 2)" },
    { "Variables", "%errorlevel%", "%errorlevel%",
      "Exit code of the last command, as a number.",
      "",
      "echo code %errorlevel%" },
    { "Variables", "%date%", "%date% %time%",
      "Current date and time, in the format of the PC's regional settings.",
      "%time:~0,8% keeps hh:mm:ss; %time: =0% replaces the leading space of the hour with a zero.",
      "echo %date% %time:~0,8% PASS>>\"%RESULT_FILE%\"" },
    { "Variables", "%random%", "%random%",
      "A random number from 0 to 32767.",
      "",
      "set /a N=%random% %% 100" },
    { "Variables", "%computername%", "%computername%",
      "Name of this PC. Also %username%, %userprofile%, %temp%, %appdata%, %programfiles%, %windir%.",
      "",
      "echo %computername% %username%" },
    { "Variables", "%PCR_RESULT_FILE%", "%PCR_RESULT_FILE%",
      "Full path of the result file chosen in Process Launcher (given to every command it starts).",
      "Use it so the same batch file writes to the file shown in the result file entry of the main window. When the batch file is started by hand the variable is empty: default to a file next to the batch file.",
      "if not defined PCR_RESULT_FILE set \"PCR_RESULT_FILE=%~dp0result.txt\"" },
    { "Files", "dir", "dir /b",
      "Lists files and folders.",
      "/b names only  /s with subfolders  /a:d only folders  /o:n sorted by name  /t:w last write time.",
      "dir /b *.log" },
    { "Files", "cd", "cd /d \"%~dp0\"",
      "Changes the current folder.",
      "/d also changes the drive. Always quote paths with spaces.",
      "cd /d \"%~dp0\"" },
    { "Files", "copy", "copy /y \"a.txt\" \"b.txt\"",
      "Copies files.",
      "/y overwrite without asking  /b binary  Exit code 1 if nothing was copied.",
      "copy /y \"%~dp0a.txt\" \"%TEMP%\\a.txt\"" },
    { "Files", "xcopy", "xcopy /e /i /y \"src\" \"dst\"",
      "Copies folders with their content.",
      "/e with subfolders (also empty)  /i the target is a folder  /y no overwrite prompt  /d copy only newer files.",
      "xcopy /e /i /y \"%~dp0data\" \"D:\\backup\\data\"" },
    { "Files", "robocopy", "robocopy \"src\" \"dst\" /e",
      "Robust copy / mirror of folders.",
      "Exit codes 0-7 are SUCCESS (bit 1 = files copied, 2 = extra files, 4 = mismatches); 8 or more = failure. So use \"if errorlevel 8\" for FAIL.",
      "robocopy \"C:\\data\" \"D:\\data\" /e /r:2 /w:2\nif errorlevel 8 (echo FAIL) else (echo PASS)" },
    { "Files", "move", "move /y \"a.txt\" \"folder\\\"",
      "Moves or renames files.",
      "",
      "move /y \"old.txt\" \"new.txt\"" },
    { "Files", "del", "del /q \"file.tmp\"",
      "Deletes files.",
      "/q no prompt  /f force read-only  /s in subfolders. Exit code is not reliable: test with \"if exist\" afterwards.",
      "del /q \"%TEMP%\\*.tmp\"" },
    { "Files", "ren", "ren \"old.txt\" \"new.txt\"",
      "Renames a file.",
      "",
      "ren result.txt result_old.txt" },
    { "Files", "mkdir", "mkdir \"folder\"",
      "Creates a folder (and the missing parents).",
      "Fails with an error if it already exists: test with if not exist first.",
      "if not exist \"%~dp0logs\" mkdir \"%~dp0logs\"" },
    { "Files", "rmdir", "rmdir /s /q \"folder\"",
      "Deletes a folder.",
      "/s with its content  /q without asking.",
      "rmdir /s /q \"%TEMP%\\mytest\"" },
    { "Files", "attrib", "attrib +r \"file\"",
      "Shows or changes file attributes.",
      "+r -r read-only  +h -h hidden  +s -s system  +a -a archive.",
      "attrib -r \"result.txt\"" },
    { "Files", "fc", "fc \"a.txt\" \"b.txt\"",
      "Compares two files line by line (/b for binary).",
      "Exit code 0 = identical, 1 = different, 2 = error. The differences are printed.",
      "fc /b \"a.bin\" \"b.bin\" >nul\nif errorlevel 1 (echo FAIL) else (echo PASS)" },
    { "Files", "comp", "comp /m \"a.bin\" \"b.bin\"",
      "Compares the content of two files byte by byte.",
      "",
      "comp /m a.bin b.bin" },
    { "Files", "tree", "tree /f",
      "Draws the folder structure.",
      "",
      "tree /f \"%~dp0\"" },
    { "Files", "where", "where python",
      "Finds an executable in the PATH.",
      "Exit code 0 when found, 1 when not: handy to check that a tool is installed.",
      "where curl >nul 2>&1 || (echo FAIL curl missing & exit /b 1)" },
    { "Files", "mklink", "mklink /d \"link\" \"target\"",
      "Creates a symbolic link (needs administrator rights).",
      "",
      "mklink /d C:\\link C:\\real" },
    { "Files", "certutil", "certutil -hashfile \"file\" SHA256",
      "Computes the hash of a file (MD5, SHA1, SHA256...).",
      "The second line of the output is the hash: compare it with the expected one.",
      "certutil -hashfile \"setup.exe\" SHA256 | findstr /i \"e3b0c442\"" },
    { "Files", "tar", "tar -xf \"a.zip\" -C \"folder\"",
      "Creates or extracts archives (zip, tar) - included in Windows 10+.",
      "",
      "tar -xf \"%~dp0data.zip\" -C \"%TEMP%\"" },
    { "Text", "find", "find /c \"text\" \"file\"",
      "Searches a fixed text in files or in the output of a command.",
      "/i ignore case  /c count the lines  /v lines that do NOT contain it. Exit code 0 found, 1 not found.",
      "type a.log | find /i \"error\" >nul && echo FAIL" },
    { "Text", "findstr", "findstr /i /c:\"text\" \"file\"",
      "Searches with simple regular expressions.",
      "/i ignore case  /c:\"a b\" literal text  /r regular expression  /v inverted  /n line numbers  /s in subfolders  /m only file names. Exit code 0 found, 1 not found.",
      "findstr /i /c:\"all tests passed\" \"%~dp0run.log\" >nul\nif errorlevel 1 (echo FAIL) else (echo PASS)" },
    { "Text", "sort", "sort \"file.txt\"",
      "Sorts lines of text.",
      "/r reverse  /+N sort from column N.",
      "type a.txt | sort" },
    { "Text", "clip", "clip",
      "Copies the output of a command to the clipboard.",
      "",
      "echo hello | clip" },
    { "Processes", "start", "start \"\" /wait \"prog.exe\"",
      "Starts a program in a new window or process.",
      "/wait waits until it ends  /b without a new window  /min minimised. The first quoted text is the window title: give \"\" before a quoted path.",
      "start \"\" /wait notepad.exe" },
    { "Processes", "tasklist", "tasklist /fi \"imagename eq notepad.exe\"",
      "Lists the running processes.",
      "/fi filter  /fo csv format. With a filter and no match it prints INFO: No tasks... (exit code still 0): search the output with find.",
      "tasklist /fi \"imagename eq notepad.exe\" | find /i \"notepad.exe\" >nul\nif errorlevel 1 (echo FAIL not running) else (echo PASS running)" },
    { "Processes", "taskkill", "taskkill /im notepad.exe /f",
      "Ends a process.",
      "/im name  /pid N  /f force  /t with its children.",
      "taskkill /im notepad.exe /f >nul 2>&1" },
    { "Processes", "timeout", "timeout /t 5 /nobreak >nul",
      "Waits a number of seconds.",
      "/t seconds (-1 = until a key)  /nobreak ignores key presses. Needs a console with input: if it complains, use \"ping -n 6 127.0.0.1 >nul\" instead.",
      "timeout /t 5 /nobreak >nul" },
    { "Processes", "schtasks", "schtasks /query /tn \"Task\"",
      "Creates, runs and queries scheduled tasks.",
      "/query /create /run /delete /end.",
      "schtasks /run /tn \"Backup\"" },
    { "Processes", "powershell", "powershell -NoProfile -Command \"...\"",
      "Runs a PowerShell command from the batch file.",
      "Use -NoProfile to start faster, -ExecutionPolicy Bypass -File x.ps1 to run a script. Its exit code is set with \"exit N\".",
      "powershell -NoProfile -Command \"if ((Get-PSDrive C).Free -gt 10GB) {exit 0} else {exit 1}\"" },
    { "Processes", "cmd", "cmd /c \"command\"",
      "Starts another command interpreter.",
      "/c runs the command and ends  /k keeps the window.",
      "cmd /c exit 3" },
    { "Network", "ping", "ping -n 1 -w 2000 host",
      "Checks that a host answers.",
      "-n count  -w timeout (ms)  -4 IPv4. Exit code 1 when there is no reply - but a reply \"Destination host unreachable\" can still return 0: also search the output for \"TTL=\".",
      "ping -n 1 -w 2000 8.8.8.8 | find \"TTL=\" >nul\nif errorlevel 1 (echo FAIL) else (echo PASS)" },
    { "Network", "ipconfig", "ipconfig /all",
      "Shows the network configuration.",
      "/release /renew /flushdns.",
      "ipconfig | find \"IPv4\"" },
    { "Network", "netstat", "netstat -ano",
      "Shows connections and listening ports with their process id.",
      "Search the output for \":8080 \" to see if a port is in use.",
      "netstat -ano | find \":443 \" | find \"LISTENING\"" },
    { "Network", "nslookup", "nslookup host",
      "Resolves a name with the DNS.",
      "",
      "nslookup example.com" },
    { "Network", "tracert", "tracert -d -h 10 host",
      "Shows the route to a host.",
      "",
      "tracert -d -h 10 example.com" },
    { "Network", "curl", "curl -s -o nul -w \"%%{http_code}\" URL",
      "Downloads a URL - included in Windows 10+.",
      "-s silent  -o file output (nul to discard)  -w \"%%{http_code}\" prints the HTTP status  -f fails (exit 22) on HTTP errors  --max-time N.",
      "for /f %%c in ('curl -s -o nul -w \"%%{http_code}\" https://example.com') do set \"CODE=%%c\"\nif \"%CODE%\"==\"200\" (echo PASS) else (echo FAIL %CODE%)" },
    { "Network", "net", "net use Z: \\\\server\\share",
      "Network shares, users and services.",
      "net use  map a share  net start / net stop  a service  net user  users.",
      "net use Z: \\\\server\\share /persistent:no" },
    { "Network", "hostname", "hostname",
      "Prints the name of this PC.",
      "",
      "hostname" },
    { "System", "sc", "sc query \"Spooler\"",
      "Queries and controls services.",
      "sc query name  shows STATE (RUNNING / STOPPED)  sc start or sc stop name  (administrator rights).",
      "sc query \"Spooler\" | find \"RUNNING\" >nul\nif errorlevel 1 (echo FAIL) else (echo PASS)" },
    { "System", "reg", "reg query \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\" /v ProductName",
      "Reads and writes the registry.",
      "reg query key /v value, reg add key /v name /t REG_SZ /d data /f, reg delete key /v name /f. Exit code 0 found, 1 not found.",
      "reg query \"HKCU\\Software\\MyApp\" >nul 2>&1\nif errorlevel 1 (echo FAIL no key) else (echo PASS)" },
    { "System", "systeminfo", "systeminfo",
      "Shows OS version, memory, hotfixes... (slow: several seconds).",
      "",
      "systeminfo | find \"OS Name\"" },
    { "System", "whoami", "whoami /groups",
      "Shows the current user (and groups / privileges).",
      "whoami /groups | find \"S-1-16-12288\" is true for an administrator prompt.",
      "whoami" },
    { "System", "ver", "ver",
      "Prints the Windows version.",
      "",
      "ver" },
    { "System", "vol", "vol C:",
      "Shows the label of a drive.",
      "",
      "vol C:" },
    { "System", "fsutil", "fsutil volume diskfree C:",
      "Volume tools (administrator rights): free space, file info.",
      "",
      "fsutil volume diskfree C:" },
    { "System", "wmic", "wmic logicaldisk get caption,freespace",
      "Queries Windows management data. Removed in recent Windows 11: prefer powershell Get-CimInstance.",
      "",
      "wmic logicaldisk get caption,freespace" },
    { "System", "shutdown", "shutdown /r /t 60",
      "Shuts down, restarts or logs off.",
      "/s shut down  /r restart  /l log off  /t seconds  /a abort.",
      "shutdown /a" },
    { "System", "assoc", "assoc .txt",
      "Shows or sets the program type of an extension.",
      "",
      "assoc .bat" },
    { "System", "path", "path",
      "Shows or sets the PATH of this batch file run.",
      "",
      "set \"PATH=%~dp0tools;%PATH%\"" },
    { "System", "prompt", "prompt $P$G",
      "Changes the console prompt.",
      "",
      "prompt $P$G" },
    { "Operators", ">", "> \"file\"",
      "Redirects the output of a command to a file (overwrites).",
      "1> is the standard output, 2> the errors. Use nul to discard.",
      "echo hello > \"a.txt\"" },
    { "Operators", ">>", ">> \"%RESULT_FILE%\"",
      "Appends the output of a command to a file (creates it if missing).",
      "The way to write the result file: every run adds a line, nothing is lost. Put it at the END: echo PASS>>\"file\" (a space before >> would be part of the text).",
      "echo %date% %time:~0,8% PASS>>\"%RESULT_FILE%\"" },
    { "Operators", "2>&1", "2>&1",
      "Sends the errors to the same place as the normal output.",
      "",
      "dir nofile >out.txt 2>&1" },
    { "Operators", "&&", "&&",
      "Runs the next command only if the previous one succeeded (exit code 0).",
      "",
      "mkdir logs && echo created" },
    { "Operators", "||", "||",
      "Runs the next command only if the previous one failed.",
      "",
      "where curl >nul 2>&1 || echo no curl" },
    { "Operators", "&", "&",
      "Runs the next command after the previous one, whatever its result.",
      "",
      "echo one & echo two" },
    { "Operators", "|", "|",
      "Pipes the output of a command into another one.",
      "",
      "type a.txt | find \"x\"" },
    { "Operators", "^", "^",
      "Escape character: prints the next character literally (^> ^| ^& ^^) and continues a line.",
      "",
      "echo a ^& b" },
    { "Operators", "nul", ">nul 2>&1",
      "The empty device: discards everything written to it.",
      "",
      "ping -n 1 host >nul 2>&1" },
    { "Templates", "PASS / FAIL block", "if errorlevel 1 (\n    echo FAIL\n    exit /b 1\n) else (\n    echo PASS\n)\n",
      "Reports PASS or FAIL from the exit code of the previous command.",
      "Print ONE of the words PASS / FAIL and exit with 0 / 1: Process Launcher searches the output (or the result file) for the expected text.",
      "somecommand\nif errorlevel 1 (\n    echo FAIL: somecommand returned %errorlevel%\n    exit /b 1\n) else (\n    echo PASS\n)" },
    { "Templates", "Result file header", "@echo off\nsetlocal\nif not defined PCR_RESULT_FILE set \"PCR_RESULT_FILE=%~dp0result.txt\"\nset \"RESULT_FILE=%PCR_RESULT_FILE%\"\nset \"TEST_NAME=%~n0\"\n",
      "Start of a batch file that logs to the result file of Process Launcher.",
      "Defines RESULT_FILE (the path given by Process Launcher, or result.txt next to the batch file when run by hand) and TEST_NAME (the name of the batch file).",
      "@echo off\nsetlocal\nif not defined PCR_RESULT_FILE set \"PCR_RESULT_FILE=%~dp0result.txt\"\nset \"RESULT_FILE=%PCR_RESULT_FILE%\"\nset \"TEST_NAME=%~n0\"" },
    { "Templates", ":log subroutine", ":log\n>>\"%RESULT_FILE%\" echo %date% %time:~0,8% [%TEST_NAME%] %*\necho %*\ngoto :eof\n",
      "Appends a line with the time to the result file and prints it.",
      "Call it as: call :log PASS message. The line in the file is \"date time [name] PASS message\". Put the subroutine AFTER the main code (after an exit /b).",
      "call :log PASS disk space ok\nexit /b 0\n:log\n>>\"%RESULT_FILE%\" echo %date% %time:~0,8% [%TEST_NAME%] %*\necho %*\ngoto :eof" },
    { "Templates", "Retry loop", "set /a TRY=0\n:retry\nset /a TRY+=1\nREM command here\nif errorlevel 1 (\n    if %TRY% lss 3 (\n        timeout /t 2 /nobreak >nul\n        goto :retry\n    )\n)\n",
      "Repeats a command up to 3 times until it succeeds.",
      "Change the limit in \"lss 3\" and the pause in the timeout line.",
      "set /a TRY=0\n:retry\nset /a TRY+=1\nping -n 1 host >nul\nif errorlevel 1 if %TRY% lss 3 goto :retry" },
    { "Templates", "Wait for file", "set /a WAITED=0\n:waitfile\nif exist \"%FILE%\" goto :found\nif %WAITED% geq 30 goto :timeout\nset /a WAITED+=1\nping -n 2 127.0.0.1 >nul\ngoto :waitfile\n:found\n:timeout\n",
      "Waits up to 30 seconds for a file to appear.",
      "Labels :found and :timeout are the two outcomes: write the PASS / FAIL code after them.",
      "set \"FILE=%~dp0done.flag\"" },
};

/*! \brief Lower case copy of \p word. */
std::string lowerWord(const wxString& word)
{
    return word.Lower().ToStdString();
}

/*! \brief Words highlighted as flow control. */
const std::set<std::string> kFlowWords = {
    "if", "else", "for", "goto", "call", "exit", "not", "exist", "defined", "errorlevel", "equ", "neq", "lss",
    "leq", "gtr", "geq", "do", "in", "shift", "setlocal", "endlocal", "pushd", "popd", "choice", "pause", "eof" };

/*! \brief Console tools highlighted as commands although they have no entry of their own. */
const std::set<std::string> kExtraCommands = {
    "echo", "set", "rem", "chdir", "md", "rd", "erase", "rename", "ftype", "label", "verify", "break", "netsh",
    "icacls", "takeown", "cscript", "wscript", "msiexec", "regsvr32", "diskpart", "chkdsk", "sfc", "dism",
    "gpupdate", "getmac", "arp", "route", "pathping", "openfiles", "query", "logoff", "msg" };

/*! \brief Every single-word entry of the table (commands and tools, not operators or templates), lower case. */
const std::set<std::string>& tableWords()
{
    static const std::set<std::string> words = [] {
        std::set<std::string> w;
        for (const BatCommand& c : kCommands) {
            const std::string cat = c.category;
            if (cat == "Operators" || cat == "Templates" || cat == "Variables") continue;
            const std::string name = c.name;
            if (name.find_first_of(" %@") == std::string::npos) w.insert(name);
        }
        return w;
    }();
    return words;
}

} // namespace

namespace BatCommands {

const std::vector<BatCommand>& all()
{
    return kCommands;
}

const std::vector<wxString>& categories()
{
    static const std::vector<wxString> names = [] {
        std::vector<wxString> n;
        for (const BatCommand& c : kCommands) {
            const wxString cat = wxString::FromUTF8(c.category);
            if (std::find(n.begin(), n.end(), cat) == n.end()) n.push_back(cat);
        }
        return n;
    }();
    return names;
}

bool isCommand(const wxString& word)
{
    const std::string w = lowerWord(word);
    if (kFlowWords.count(w)) return false;
    return tableWords().count(w) != 0 || kExtraCommands.count(w) != 0;
}

bool isFlow(const wxString& word)
{
    return kFlowWords.count(lowerWord(word)) != 0;
}

wxString infoText(const BatCommand& command)
{
    wxString text = wxString::FromUTF8(command.name) + "\n\n" + wxString::FromUTF8(command.summary);
    const wxString details = wxString::FromUTF8(command.details);
    if (!details.empty()) text += "\n\n" + details;
    const wxString example = wxString::FromUTF8(command.example);
    if (!example.empty()) text += "\n\nExample:\n" + example;
    return text;
}

} // namespace BatCommands
